apiVersion: platform.internal/v1alpha1
kind: Environment
metadata:
  name: billing-dev
spec:
  owner:
    contact: '#team-billing'
    team: billing
  resources:
    cpu: "0"
    memory: "0"
  tier: dev
status: {}
